const langs = [
    {value: 'apache', className: 'apache', text: 'Apache'},
    {value: 'bash', className: 'bash', text: 'Bash'},
    {value: 'cs', className:'cs', text: 'C#'},
    {value: 'cpp', className: 'cpp', text: 'C++'},
    {value: 'css', className: 'css', text: 'CSS'},
    {value: 'coffescript', className: 'coffescript', text: 'CoffeScript'},
    {value: 'diff', className: 'diff', text: 'Diff'},
    {value: 'xml/html', className: 'xml', text: 'HTML/XML'},
    {value: 'http', className: 'http', text: 'HTTP'},
    {value: 'ini', className: 'ini', text: 'Ini'},
    {value: 'json', className: 'json', text: 'JSON'},
    {value: 'javascript/js/jsx', className: 'javascript', text: 'JavaScript'},
    {value: 'java', className: 'java', text: 'Java'},
    {value: 'makefile', className: 'makefile', text: 'Makefile'},
    {value: 'markdown', className: 'markdown', text: 'Markdown'},
    {value: 'nginx', className: 'nginx', text: 'Nginx'},
    {value: 'objectivec', className: 'objectivec', text: 'Objective-C'},
    {value: 'php', className: 'php', text: 'PHP'},
    {value: 'perl', className: 'perl', text: 'Perl'},
    {value: 'python', className: 'python', text: 'Python'},
    {value: 'ruby', className: 'ruby', text: 'Ruby'},
    {value: 'sql', className: 'sql', text: 'SQL'},
    {value: 'shell', className: 'shell', text: 'Shell'}]
